version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - flask_network

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/flask_microservices?authSource=admin
    depends_on:
      - mongodb
    networks:
      - flask_network
    ports:
      - "5000:5000"

  product_service:
    build: ./product_service
    container_name: product_service
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/flask_microservices?authSource=admin
    depends_on:
      - mongodb
    networks:
      - flask_network
    ports:
      - "5001:5001"

  order_service:
    build: ./order_service
    container_name: order_service
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/flask_microservices?authSource=admin
    depends_on:
      - mongodb
    networks:
      - flask_network
    ports:
      - "5002:5002"

networks:
  flask_network:
    driver: bridge
